# Generated by Django 5.2.8 on 2025-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.topic', verbose_name='Темы'),
        ),
    ]
